name: CD-to-DockerHub
on:
  push:
    branches: [ main ]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create timestamp
      run: echo "TS=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

    - name: Build image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/python-app
        docker build -t $IMAGE:latest .

    - name: Tag with timestamp
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/python-app
        docker tag $IMAGE:latest $IMAGE:${{ env.TS }}

    - name: Push images
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/python-app
        docker push $IMAGE:latest
        docker push $IMAGE:${{ env.TS }}
